baseURL = "http://example.org/"
languageCode = "ko"
title = "강소팟"
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "일과 삶에 대한 진지한 대화. 강단과 소신 팟캐스트."
  favicon = "images/main-thumbnail.jpg"